# Generated by Django 5.2.14 on 2026-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('bucket_size', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'unique_together': {('tenant_id', 'bucket_start', 'bucket_size', 'source', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='ingestion_e_tenant__e9f1a9_idx'), models.Index(fields=['source'], name='ingestion_e_source_9ad9d7_idx'), models.Index(fields=['event_type'], name='ingestion_e_event_t_4087ef_idx')],
            },
        ),
    ]
