# Generated by Django 5.2.14 on 2026-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['tenant_id', 'bucket_start'], name='ingestion_a_tenant__074195_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['tenant_id', 'event_type'], name='ingestion_a_tenant__cbc4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['tenant_id', 'source'], name='ingestion_a_tenant__359b27_idx'),
        ),
    ]
